[package]
name = "koto"
version = "0.15.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2021"
license = "MIT"
description = "A simple, expressive, embeddable programming language"
homepage = "https://koto.dev"
repository = "https://github.com/koto-lang/koto"
keywords = ["scripting", "language", "koto"]

[features]
default = ["arc"]
arc = ["koto_runtime/arc"]
rc = ["koto_runtime/rc"]

[dependencies]
koto_bytecode = { path = "../bytecode", version = "^0.15.0", default-features = false }
koto_parser = { path = "../parser", version = "^0.15.0", default-features = false }
koto_runtime = { path = "../runtime", version = "^0.15.0", default-features = false }
rhai = "*"
dunce = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
koto_geometry = { path = "../../libs/geometry" }
koto_talib = { path = "../../libs/talib" }

koto_test_utils = { path = "../test_utils" }

anyhow = { workspace = true }
criterion = { workspace = true }
mimalloc = { workspace = true }

[[bench]]
name = "koto_benchmark"
harness = false
test = true
