[package]
name = "koto_test_utils"
version = "0.15.0"
edition = "2021"
authors = ["irh <ian.r.hobson@gmail.com>"]
license = "MIT"
description = "Testing utilities for the Koto programming language"
homepage = "https://koto.dev"
repository = "https://github.com/koto-lang/koto"
keywords = ["scripting", "language", "koto"]

[dependencies]
itertools = { workspace = true }
pulldown-cmark = { workspace = true }

[dependencies.koto_bytecode]
path = "../../crates/bytecode"
version = "^0.15.0"
default-features = false

[dependencies.koto_runtime]
path = "../../crates/runtime"
version = "^0.15.0"
default-features = false
