[package]
name = "koto_parser"
version = "0.15.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2021"
license = "MIT"
description = "The parser used by the Koto programming language"
homepage = "https://koto.dev"
repository = "https://github.com/koto-lang/koto"
keywords = ["scripting", "language", "koto"]

[features]
default = ["arc"]
arc = ["koto_memory/arc"]
rc = ["koto_memory/rc"]

# Panicking be useful during development, e.g. to see the backtrace that led to the error
panic_on_parser_error = []

[dependencies]
koto_lexer = { path = "../lexer", version = "^0.15.0" }
koto_memory = { path = "../memory", version = "^0.15.0", default-features = false }

derive-name = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
unicode-segmentation = { workspace = true }
nom = "8.0.0-alpha2"
bytes = "1.7.1"
